# version format
version: 1.0.{build}

# Do not build on tags
skip_tags: true


build_script:
  - cd Build
  - Package.build.cmd %APPVEYOR_BUILD_VERSION%

artifacts:
  - path: Releases\*.nupkg
  
deploy:
  provider: NuGet
  server:
  api_key:
    secure: 
  artifact: /.*\.nupkg/